# Generated by Django 4.1.7 on 2023-03-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image_rename_title_section_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
