# Generated by Django 4.1.7 on 2023-03-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='section_images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
